import { Event, Bucket } from '../types';

export const CITIES = ['Recife, PE', 'Olinda, PE', 'João Pessoa, PB', 'Caruaru, PE'];

export const BUCKETS: Bucket[] = [
  { id: 'soon', label: 'Nos próximos dias', range: '8–12 jun' },
  { id: 'weekend', label: 'Este fim de semana', range: '13–14 jun' },
  { id: 'next', label: 'Próxima semana', range: '15–21 jun' },
  { id: 'two', label: 'Daqui a 2 semanas', range: '22–28 jun' },
  { id: 'july', label: 'Em julho', range: 'a partir de 1 jul' },
];

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'e1', sport: 'pelada', bucket: 'soon',
    title: 'Racha de Quarta · Society',
    day: 'Qua', date: '10 jun', time: '20:00',
    neighborhood: 'Parque da Jaqueira', city: 'Recife, PE',
    meta: 'Society 7v7', level: 'Livre', price: 'R$ 20',
    going: 9, spots: 14, host: 'Diego Albuquerque', hostInitial: 'D',
    people: ['JR', 'TS', 'MA', 'BL'],
    blurb: 'Racha fixo de meio de semana. Times equilibrados na hora, colete por conta da organização. Chega 10 min antes pra esquentar.',
  },
  {
    id: 'e2', sport: 'ciclismo', bucket: 'soon',
    title: 'Pedal Noturno Marco Zero',
    day: 'Qui', date: '11 jun', time: '19:30',
    neighborhood: 'Recife Antigo', city: 'Recife, PE',
    meta: '22 km · ritmo leve', level: 'Iniciante', price: 'Grátis',
    going: 64, host: 'Bike Recife', hostInitial: 'B',
    people: ['CA', 'LP', 'RS', 'VM'],
    blurb: 'Pedal tranquilo pela orla e Recife Antigo, com batedores e ponto de apoio. Luzes obrigatórias. Encontro na frente do Marco Zero.',
  },
  {
    id: 'e3', sport: 'corrida', bucket: 'weekend',
    title: 'Night Run Boa Viagem',
    day: 'Sáb', date: '13 jun', time: '18:00',
    neighborhood: 'Orla de Boa Viagem', city: 'Recife, PE',
    meta: '5K · 10K', level: 'Todos', price: 'R$ 79',
    going: 312, host: 'RunPE', hostInitial: 'R', featured: true,
    people: ['AL', 'FM', 'GP', 'TC'],
    blurb: 'Corrida noturna à beira-mar com largada única, hidratação no percurso e kit com camiseta e medalha. Percurso plano e iluminado.',
  },
  {
    id: 'e4', sport: 'beach', bucket: 'weekend',
    title: 'Beach Tennis Open · Iniciantes',
    day: 'Sáb', date: '13 jun', time: '09:00',
    neighborhood: 'Praia de Boa Viagem', city: 'Recife, PE',
    meta: 'Duplas · iniciante', level: 'Iniciante', price: 'R$ 40',
    going: 28, spots: 32, host: 'BT Clube', hostInitial: 'B',
    people: ['NS', 'PH', 'CL'],
    blurb: 'Torneio descontraído pra quem está começando. Inscrição por dupla, raquetes de empréstimo disponíveis. Premiação simbólica.',
  },
  {
    id: 'e5', sport: 'pelada', bucket: 'weekend',
    title: 'Fut das Minas · Domingo',
    day: 'Dom', date: '14 jun', time: '08:00',
    neighborhood: 'Quadra da Várzea', city: 'Recife, PE',
    meta: 'Society 7v7', level: 'Livre', price: 'R$ 15',
    going: 11, spots: 14, host: 'Marina Costa', hostInitial: 'M',
    people: ['JU', 'Ka', 'BE'],
    blurb: 'Pelada só de mulheres, todo domingo de manhã. Ambiente acolhedor, todos os níveis bem-vindos. Confirma presença pra fechar os times.',
  },
  {
    id: 'e6', sport: 'basquete', bucket: 'next',
    title: 'Basquete 3x3 no Parque',
    day: 'Sáb', date: '20 jun', time: '17:00',
    neighborhood: 'Parque da Jaqueira', city: 'Recife, PE',
    meta: '3x3 · livre', level: 'Livre', price: 'Grátis',
    going: 22, host: 'Liga 3x3', hostInitial: 'L',
    people: ['TH', 'RA', 'DS'],
    blurb: 'Pega-racha de 3x3 na quadra do parque. Vai chegando e montando time. Bola e coletes com a organização.',
  },
  {
    id: 'e7', sport: 'ciclismo', bucket: 'next',
    title: 'Giro da Boa Viagem 40K',
    day: 'Dom', date: '21 jun', time: '06:00',
    neighborhood: 'Orla de Boa Viagem', city: 'Recife, PE',
    meta: '40 km · moderado', level: 'Intermediário', price: 'Grátis',
    going: 96, host: 'Pedal Sul', hostInitial: 'P',
    people: ['EM', 'GV', 'LT', 'CR'],
    blurb: 'Treino longo de domingo em ritmo moderado, sem deixar ninguém pra trás. Grupo fechado, ponto de regroup a cada 10 km.',
  },
  {
    id: 'e8', sport: 'trilha', bucket: 'next',
    title: 'Trilha do Catimbau ao Amanhecer',
    day: 'Sáb', date: '20 jun', time: '05:00',
    neighborhood: 'Vale do Catimbau', city: 'Buíque, PE',
    meta: '8 km · moderada', level: 'Intermediário', price: 'R$ 120',
    going: 18, spots: 24, host: 'Trilheiros PE', hostInitial: 'T',
    people: ['AN', 'BR', 'Cí'],
    blurb: 'Travessia guiada para ver o nascer do sol no vale. Valor inclui transporte saindo do Recife e guia local. Leve água e lanche.',
  },
  {
    id: 'e9', sport: 'corrida', bucket: 'two',
    title: 'Meia Maratona do Recife',
    day: 'Dom', date: '28 jun', time: '05:30',
    neighborhood: 'Marco Zero', city: 'Recife, PE',
    meta: '21K · 10K · 5K', level: 'Todos', price: 'R$ 129',
    going: 1240, host: 'Recife Runners', hostInitial: 'R', featured: true,
    people: ['FL', 'MM', 'PA', 'SO'],
    blurb: 'A clássica do calendário. Três distâncias, largadas separadas, cronometragem por chip, kit completo e estrutura de apoio no percurso.',
  },
  {
    id: 'e10', sport: 'volei', bucket: 'two',
    title: 'Vôlei de Praia · Racha Aberto',
    day: 'Sáb', date: '27 jun', time: '15:00',
    neighborhood: 'Praia do Pina', city: 'Recife, PE',
    meta: 'Duplas · livre', level: 'Livre', price: 'Grátis',
    going: 16, host: 'Areia & Sol', hostInitial: 'A',
    people: ['Vi', 'Lu', 'Ro'],
    blurb: 'Rodízio de duplas na areia, todos os níveis. Rede montada às 15h. Chega, anota o nome na lista e entra na próxima.',
  },
  {
    id: 'e11', sport: 'corrida', bucket: 'july',
    title: 'Circuito das Praias · Etapa Recife 10K',
    day: 'Sáb', date: '04 jul', time: '06:00',
    neighborhood: 'Orla de Boa Viagem', city: 'Recife, PE',
    meta: '10K', level: 'Todos', price: 'R$ 99',
    going: 540, host: 'Circuito BR', hostInitial: 'C',
    people: ['DA', 'Es', 'Fá'],
    blurb: 'Etapa do circuito nacional à beira-mar. Percurso plano homologado, hidratação e frutas na chegada. Kit retirado na semana da prova.',
  },
  {
    id: 'e12', sport: 'pelada', bucket: 'july',
    title: 'Copa Pelada de Inverno',
    day: 'Dom', date: '12 jul', time: '08:00',
    neighborhood: 'Society Imbiribeira', city: 'Recife, PE',
    meta: 'Society 7v7 · torneio', level: 'Competitivo', price: 'R$ 200',
    going: 8, spots: 12, host: 'Pelada League', hostInitial: 'P',
    people: ['Ti', 'Eq', 'Ti'],
    blurb: 'Torneio de inverno em formato de grupos + mata-mata, um domingo inteiro. Inscrição por time (até 10 atletas). Premiação e troféu.',
    unit: 'times',
  },
];
